server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
          git:
            uri: https://github.com/adongs/spring-cloud-config.git
            username: 1286630069@qq.com
            password: yudong197156
    bus:
      trace:
        enabled: true
      enabled: true
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
management:
  endpoints:
    web:
      exposure:
        include: bus-env,bus-refresh